name: mobile_app
description: "Mistri Interior Attendance App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # These are the tools we need
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true